const Label = {
    name: 'Name',
    email: 'Email',
    password: 'Password',
    comfirmPassword: 'Comfirm password',
    signUp: 'Sign up',
    signUpPara: 'Enetr your email and password to create an account.',
    signIn: 'Sign in',
    signInPara: 'Enter your email and password to sign in.',
    forgotPassword: 'Forgot password?',
    dontHaveAnAccount: `Don't have an account?`,
    alreadyHaveAnAccount: `Already have an account?`,
    firstName: 'First name',
    lastName: 'Last name',
    mobileNumber: 'Mobile number',
    address: 'Address',
    city: 'City',
    postCode: 'Post code',
    totalExperience: 'Total experience',
    currentSalary: 'Current salary',
    preferredSalary: 'Preferred salary',
    preferredLocation: 'Preferred location',
    selectRoles: 'Select roles',
    jobType: 'Job type',
    intro1: 'Find qualified chefs & front of house staff today',
    intro2: 'Quick registration process. Work whenever, where ever!',
    intro3: 'Welcome to Chef Zone.\nSimply LOOK BOOK COOK',
    welcomeScreenHeader: 'Welcome to',
    brandName: 'Chef Zone',
    welcomeScreenButtonText1: `I'm a job seeker`,
    welcomeScreenButtonText2: `I'm a business`,
    welcomeScreenButtonText3: `Browse jobs`,
    welcomeScreenButtonText4: `CV Live`,
}

export default Label;